server:
  port: 8080

ollama:
  api:
    url: ${OLLAMA_URL}

logging:
  level:
    org.springframework.security: TRACE

spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  ai:
    vectorstore:
      chroma:
        client:
          host: ${CHROMA_HOST}
          port: ${CHROMA_PORT}
        collection-name: recluter_vectors
        initialize-schema: true

jwt:
  secret: ${SECRET_KEY}
  expiration: 86400000